# Generated by Django 3.1.1 on 2020-10-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('imagen', models.ImageField(null=True, upload_to='Mision y Visión')),
                ('mision', models.CharField(max_length=300)),
                ('vision', models.CharField(max_length=300)),
            ],
        ),
    ]
