# Generated by Django 3.1.1 on 2020-10-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_misionvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionvision',
            name='texto2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='misionvision',
            name='texto',
            field=models.CharField(max_length=250),
        ),
    ]
