# Generated by Django 3.1.1 on 2020-10-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201018_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misionvision',
            old_name='texto',
            new_name='texto1',
        ),
    ]
