# Generated by Django 3.1.1 on 2020-11-04 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201018_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)])),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagen', models.ImageField(null=True, upload_to='Insumo')),
                ('descripcion', models.TextField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
