# Generated by Django 3.1.1 on 2020-11-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='Insumo'),
            preserve_default=False,
        ),
    ]
