# Generated by Django 3.1.1 on 2020-12-09 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201104_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('asunto', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Solicitud'], [1, 'Reclamo'], [2, 'Sugerencia']])),
                ('mensaje', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
